spring:
  application:
    name: onestock
  config:
    import: BE-one-stock-config/application-local-db.yml
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false
    clean-disabled: false
    out-of-order: true